## 📝 Instrucciones ##

**Análisis de sentimientos**

Los modelos Naive Bayes son muy útiles cuando queremos analizar sentimientos, clasificar textos en tópicos o recomendaciones, ya que las características de estos desafíos cumplen muy bien con los supuestos teóricos y metodológicos del modelo.

En este proyecto practicarás con un conjunto de datos para crear un clasificador de reseñas de la tienda de Google Play.

### Paso 1: Carga del conjunto de datos ###

El conjunto de datos se puede encontrar en esta carpeta de proyecto bajo el nombre playstore_reviews.csv. Puedes cargarlo en el código directamente desde el sigiente enlace:

https://raw.githubusercontent.com/4GeeksAcademy/naive-bayes-project-tutorial/main/playstore_reviews.csv

O descargarlo y añadirlo a mano en tu repositorio. En este conjunto de datos encontrarás las siguientes variables:

    -package_name. Nombre de la aplicación móvil (categórico)

    -review. Comentario sobre la aplicación móvil (categórico)

    -polarity. Variable de clase (0 o 1), siendo 0 un comentario negativo y 1, positivo (categórico numérico)

In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB, BernoulliNB, GaussianNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score 
from sklearn.ensemble import RandomForestClassifier

In [11]:
df = pd.read_csv('../data/raw/playstore_reviews.csv')
df.head()

,package_name,review,polarity
0,com.facebook.katana,privacy at least put some option appear offli...,0
1,com.facebook.katana,"messenger issues ever since the last update, ...",0
2,com.facebook.katana,profile any time my wife or anybody has more ...,0
3,com.facebook.katana,the new features suck for those of us who don...,0
4,com.facebook.katana,forced reload on uploading pic on replying co...,0

### Paso 2: Estudio de variables y su contenido ###

En este caso, tenemos solo 3 variables: 2 predictoras y una etiqueta dicotómica. De las dos predictoras, realmente solo nos interesa la parte del comentario, ya que el hecho de clasificar un comentario en positivo o negativo dependerá de su contenido, no de la aplicación de la que se haya escrito. Por lo tanto, la variable package_name habría que eliminarla.

Cuando trabajamos con textos como en este caso, no tiene sentido hacer un EDA, el proceso es diferente, ya que la única variable que nos interesa es la que contiene el texto. En otros casos en los que el texto formase parte de un conjunto complejo con otras variables predictoras numéricas y el objetivo de predicción sea distinto, entonces tiene sentido aplicar un EDA.

Sin embargo, no podemos trabajar con texto plano, antes hay que procesarlo. Este proceso consta de varios pasos:

Eliminar espacios y convertir a minúsculas el texto:

**df["column"] = df["column"].str.strip().str.lower()**

Dividir el conjunto de datos en train y test: X_train, X_test, y_train, y_test

Transformar el texto en una matriz de recuento de palabras. Esta es una forma de obtener características numéricas a partir del texto. Para ello, utilizamos el conjunto de train para entrenar el transformador y la aplicamos en test:

**vec_model = CountVectorizer(stop_words = "english")**

**X_train = vec_model.fit_transform(X_train).toarray()**

**X_test = vec_model.transform(X_test).toarray()**

Una vez hayamos terminado tendremos listas las predictoras para entrenar el modelo.

In [12]:
#Eliminamos la clumna package_name que no se va a usar
df = df.drop(columns=['package_name'])
df.head()

                                              review  polarity
0   privacy at least put some option appear offli...         0
1   messenger issues ever since the last update, ...         0
2   profile any time my wife or anybody has more ...         0
3   the new features suck for those of us who don...         0
4   forced reload on uploading pic on replying co...         0

In [14]:
#Limpiar el texto: eliminar espacios y convetir a minúsculas
df['review'] = df['review'].str.strip().str.lower()
df.head()

                                              review  polarity
0  privacy at least put some option appear offlin...         0
1  messenger issues ever since the last update, i...         0
2  profile any time my wife or anybody has more t...         0
3  the new features suck for those of us who don'...         0
4  forced reload on uploading pic on replying com...         0

In [ ]:
#Verificar que el texto esté limpio
print("Valores nulos:", df['review'].isnull().sum())
print("Valores vacíos:", (df['review'] == '').sum())

Valores nulos: 0
Valores vacíos: 0

In [18]:
X = df['review']
y = df['polarity']

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
vec_model = CountVectorizer(stop_words='english')
X_train_vect = vec_model.fit_transform(X_train).toarray()
X_test_vect = vec_model.transform(X_test).toarray()

print("X_train_vect shape:", X_train_vect.shape)
print("X_test_vect shape:", X_test_vect.shape)

X_train_vect shape: (712, 3310)
X_test_vect shape: (179, 3310)

### Paso 3: Construye un Naive Bayes ###

Comienza a resolver el problema implementando un modelo del que tendrás que elegir cuál de las tres implementaciones utilizar: GaussianNB, MultinomialNB o BernoulliNB, según lo que hemos estudiado en el módulo. Prueba ahora a entrenarlo con las dos otras implementaciones y confirma si el modelo que has elegido es el adecuado.

**MultinomialNB**

In [26]:
mnb = MultinomialNB()
mnb.fit(X_train_vect, y_train)

MultinomialNB()

In [ ]:
#Predicciones
y_pred_mnb = mnb.predict(X_test_vect)

print("Accuracy MultinomialNB:", accuracy_score(y_test, y_pred_mnb))
print("Classification Report:\n", classification_report(y_test, y_pred_mnb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_mnb))

Accuracy MultinomialNB: 0.8156424581005587
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.90      0.87       126
           1       0.73      0.60      0.66        53

    accuracy                           0.82       179
   macro avg       0.79      0.75      0.77       179
weighted avg       0.81      0.82      0.81       179

Confusion Matrix:
 [[114  12]
 [ 21  32]]

**GaussianNB**

In [33]:
gnb = GaussianNB()
gnb.fit(X_train_vect, y_train)
y_pred_gnb = gnb.predict(X_test_vect)
print("Accuracy GaussianNB:", accuracy_score(y_test, y_pred_gnb))
print("Classification Report:\n", classification_report(y_test, y_pred_gnb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_gnb))

Accuracy GaussianNB: 0.8044692737430168
Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.88      0.86       126
           1       0.69      0.62      0.65        53

    accuracy                           0.80       179
   macro avg       0.77      0.75      0.76       179
weighted avg       0.80      0.80      0.80       179

Confusion Matrix:
 [[111  15]
 [ 20  33]]

**Bernoulli**

In [34]:
bnb = BernoulliNB()
bnb.fit(X_train_vect, y_train)
y_pred_bnb = bnb.predict(X_test_vect)
print("Accuracy BernoulliNB:", accuracy_score(y_test, y_pred_bnb))
print("Classification Report:\n", classification_report(y_test, y_pred_bnb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_bnb))

Accuracy BernoulliNB: 0.770949720670391
Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.93      0.85       126
           1       0.70      0.40      0.51        53

    accuracy                           0.77       179
   macro avg       0.74      0.66      0.68       179
weighted avg       0.76      0.77      0.75       179

Confusion Matrix:
 [[117   9]
 [ 32  21]]

**Comparación de modelos Naive Bayes**

| Métrica         | MultinomialNB | GaussianNB | BernoulliNB |
|-----------------|---------------|------------|-------------|
| Accuracy        | 0.816         | 0.804      | 0.771       |
| Precision Clase 0 | 0.84        | 0.85       | 0.79        |
| Precision Clase 1 | 0.73        | 0.69       | 0.70        |
| Recall Clase 0    | 0.90        | 0.88       | 0.93        |
| Recall Clase 1    | 0.60        | 0.62       | 0.40        |
| F1-score Clase 0  | 0.87        | 0.86       | 0.85        |
| F1-score Clase 1  | 0.66        | 0.65       | 0.51        |

1. MultinomialNB

_Mejor accuracy general (0.816)._

Teóricamente este modelo asume que los datos son conteos o frecuencias de palabras, lo cual coincide bien con el método CountVectorizes que fue el que se usó para vectorizar el texto. Los resultados parecen confirmar esta conveniencia respecto a los otros 2 métodos.

2. GaussianNB

Similar a MultinomialNB, pero ligeramente menor precisión y recall en la clase positiva.

Menos adecuado porque asume que las características siguen distribución normal, lo cual no se cumple en datos de conteo de palabras.

3. BernoulliNB

Mejor en detectar la clase negativa (recall 0 = 0.93) pero muy débil en la clase positiva (recall 1 = 0.40).

Funciona mejor con datos binarios (presencia/ausencia de palabra), pero pierde información del conteo de palabras, por eso falla con comentarios positivos.


**Conclusión: MultinomialNB es el modelo más equilibrado para este dataset ya que detecta correctamente la mayoría de los comentarios negativos y positivos. Es consistente con la naturaleza del texto y el vectorizado de conteos. GaussianNB y BernoulliNB son alternativas, pero no superan el desempeño general de MultinomialNB.**

### Paso 4: Optimiza el modelo anterior ###

Después de entrenar el modelo en sus tres implementaciones, elige la mejor opción y trata de optimizar sus resultados con un random forest, si es posible

In [37]:
random_forest = RandomForestClassifier(n_estimators=100, random_state=42)
random_forest.fit(X_train_vect, y_train)

RandomForestClassifier(random_state=42)

In [39]:
y_pred_random_forest = random_forest.predict(X_test_vect)
accuracy_random_forest = accuracy_score(y_test, y_pred_random_forest)
print("Accuracy Random Forest:", accuracy_random_forest)
print("Classification Report:\n", classification_report(y_test, y_pred_random_forest))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_random_forest))

Accuracy Random Forest: 0.7988826815642458
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.83      0.85       126
           1       0.64      0.74      0.68        53

    accuracy                           0.80       179
   macro avg       0.76      0.78      0.77       179
weighted avg       0.81      0.80      0.80       179

Confusion Matrix:
 [[104  22]
 [ 14  39]]

**Comparación de modelos de clasificación (vertical)**

| Métrica           | MultinomialNB | GaussianNB | BernoulliNB | Random Forest |
|------------------|---------------|------------|-------------|---------------|
| Accuracy          | 0.816         | 0.804      | 0.771       | 0.799         |
| Precision Clase 0 | 0.84          | 0.85       | 0.79        | 0.88          |
| Precision Clase 1 | 0.73          | 0.69       | 0.70        | 0.64          |
| Recall Clase 0    | 0.90          | 0.88       | 0.93        | 0.83          |
| Recall Clase 1    | 0.60          | 0.62       | 0.40        | 0.74          |
| F1-score Clase 0  | 0.87          | 0.86       | 0.85        | 0.85          |
| F1-score Clase 1  | 0.66          | 0.65       | 0.51        | 0.68          |

MultinomialNB sigue siendo el modelo más equilibrado. Random Forest detecta mejor la clase positiva (recall = 0.74) pero empeora la clase negatia (recall = 0.83). No mejora el desempeño general y es más costoso computacionalmente.

### Paso 5: Guarda el modelo ###

Almacena el modelo en la carpeta correspondiente.

In [42]:
import joblib
joblib.dump(mnb, "../models/playstore_reviews/multinomial_nb_model.pkl")

['../models/playstore_reviews/multinomial_nb_model.pkl']

### Paso 6: Explora otras alternativas ###

¿Qué otros modelos de los que hemos estudiado podrías utilizar para intentar superar los resultados de un Naive Bayes? Arguméntalo y entrena el modelo.

In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier

In [48]:
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train_vect, y_train)

LogisticRegression(max_iter=1000)

In [49]:
y_pred_log_reg = log_reg.predict(X_test_vect)
accuracy_log_reg = accuracy_score(y_test, y_pred_log_reg)
print("Accuracy Logistic Regression:", accuracy_log_reg)
print("Classification Report:\n", classification_report(y_test, y_pred_log_reg))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_log_reg))

Accuracy Logistic Regression: 0.8324022346368715
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.84      0.88       126
           1       0.68      0.81      0.74        53

    accuracy                           0.83       179
   macro avg       0.80      0.83      0.81       179
weighted avg       0.85      0.83      0.84       179

Confusion Matrix:
 [[106  20]
 [ 10  43]]

In [52]:
grad_boost = GradientBoostingClassifier(n_estimators=100, random_state=42)
grad_boost.fit(X_train_vect, y_train)

GradientBoostingClassifier(random_state=42)

In [53]:
y_pred_grad_boost = grad_boost.predict(X_test_vect)
accuracy_grad_boost = accuracy_score(y_test, y_pred_grad_boost)
print("Accuracy Gradient Boosting:", accuracy_grad_boost)
print("Classification Report:\n", classification_report(y_test, y_pred_grad_boost))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_grad_boost))

Accuracy Gradient Boosting: 0.7318435754189944
Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.83      0.81       126
           1       0.55      0.49      0.52        53

    accuracy                           0.73       179
   macro avg       0.67      0.66      0.67       179
weighted avg       0.72      0.73      0.73       179

Confusion Matrix:
 [[105  21]
 [ 27  26]]

| Modelo                  | Métrica           | Clase 0 (negativo) | Clase 1 (positivo) | Accuracy |
|-------------------------|-----------------|------------------|------------------|---------|
| MultinomialNB           | Precision       | 0.84             | 0.73             | 0.816   |
|                         | Recall          | 0.90             | 0.60             |         |
|                         | F1-score        | 0.87             | 0.66             |         |
| GaussianNB              | Precision       | 0.85             | 0.69             | 0.804   |
|                         | Recall          | 0.88             | 0.62             |         |
|                         | F1-score        | 0.86             | 0.65             |         |
| BernoulliNB             | Precision       | 0.79             | 0.70             | 0.771   |
|                         | Recall          | 0.93             | 0.40             |         |
|                         | F1-score        | 0.85             | 0.51             |         |
| Random Forest           | Precision       | 0.88             | 0.64             | 0.799   |
|                         | Recall          | 0.83             | 0.74             |         |
|                         | F1-score        | 0.85             | 0.68             |         |
| Logistic Regression     | Precision       | 0.91             | 0.68             | 0.832   |
|                         | Recall          | 0.84             | 0.81             |         |
|                         | F1-score        | 0.88             | 0.74             |         |
| Gradient Boosting       | Precision       | 0.80             | 0.55             | 0.732   |
|                         | Recall          | 0.83             | 0.49             |         |
|                         | F1-score        | 0.81             | 0.52             |         |

**Conclusión: Entre todos los métodos, Logistic Regression es la opción más equilibrada y efectiva, especialmente si nos interesa detectar correctamente tanto comentarios positivos como negativos.**